#Apis will be created here. api will make communication between mobile/web app & LLM
#api endpoints are found in http://localhost:8000/docs#/
from fastapi import FastAPI
from langserve import add_routes
from langchain_community.llms import Ollama
from langchain.prompts import ChatPromptTemplate
import uvicorn


app=FastAPI(
    title="Langchain Server",
    version="1.0",
    decsription="A simple API Server"
)


##ollama llama3.2:1b
llm=Ollama(model="llama3.2:1b")

prompt2=ChatPromptTemplate.from_template("Write me an poem about {topic} for a 5 years child with 100 words")

add_routes(
    app,
    prompt2|llm,
    path="/golam"   #api endpoints will be generated by this path
)


if __name__=="__main__":
    uvicorn.run(app,host="localhost",port=8000)